Reddit/config/routes.rb
Rails.application.routes.draw do
  resources :subs, only: [:show, :index] do
    resources :posts
  end
  resources :users do
    resources :subs, except: [:show, :index]
  end
  resource :session, only: [:new, :create, :destroy]

end

Reddit/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true
  validates :title, uniqueness: true

  belongs_to :sub

  belongs_to :author


  has_many :post_subs

  has_many :subs, through: :post_subs
end

Reddit/app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :sub_id, :post_id, presence: true
  validates :sub_id, uniqueness: { scope: :post_id }

  belongs_to :sub

  belongs_to :post
end

Reddit/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :posts, through: :post_subs

  has_many :post_subs
end

Reddit/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :username, uniqueness: true
  validates :password, length: {minimum: 6}, allow_nil: true

  after_initialize :ensure_session_token
  attr_reader :password

  has_many :posts

  has_many :subs, dependent: :destroy,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    return nil unless @user
    @user = @user.is_password?(password) ? @user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
end

Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    @user = User.find_by_session_token(session[:session_token])
    @user
  end

  def require_login
    current_user
    redirect_to subs_url if @user
  end

end

Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    set_post
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.sub_id = [ ]
  end

  # GET /posts/1/edit
  def edit
    set_post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.sub_id = params[:sub_id]
    if @post.save
      post_params[:sub_id].each do |sub_id|
        post = PostSub.new(post_id: @post.id, sub_id: sub_id)
        post.save
      end
      debugger
      redirect_to sub_url(@post.sub_id)
    else
      flash[:error] = @post.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    set_post
      if @post.update(post_params)
        redirect_to sub_url(@post.sub_id)
      else
        flash[:error] = @post.errors.full_messages
        render :edit
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    set_post
    @post.destroy
    redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :content, :author_id, :sub_id => [])
    end
end

Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(session_params[:username], session_params[:password])
    if @user
      session[:session_token] = @user.reset_session_token!
      redirect_to subs_url
    else
      render :new, text: 'Invalid login or password'
    end
  end

  def destroy
    @user = current_user
    @user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end


  private

  def session_params
    params.require(:user).permit(:username, :password, :session_token)
  end
end

Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :edit, :update, :destroy]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.all
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
    set_sub
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  # GET /subs/1/edit
  def edit
    @sub = Sub.new
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else
      flash[:error] = @sub.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
    set_sub
      if @sub.update(sub_params)
        redirect_to subs_url
      else
        flash[:error] = @sub.errors.full_messages
        render :edit
      end
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    set_sub
    @sub.destroy
    redirect_to subs_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_params
      params.require(:sub).permit(:title, :description, :moderator_id, :user_id)
    end
end

Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:index]

  def logged_in?
    redirect_to new_session_url
  end

  def index
    @users = User.all
  end

  def show
    set_user
  end


  def new
    @user = User.new
  end


  def edit
    set_user
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_url
    else
      flash[:error] = @user.errors.full_messages
      render :new
    end
  end


  def update
    set_user
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end


  def destroy
    set_user
    @user.destroy
    redirect_to users_url
  end

  private

    def set_user
      @user = User.find(params[:id])
    end


    def user_params
      params.require(:user).permit(:username, :password_digest, :session_token, :password)
    end
end

Reddit/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    text = '<input type="hidden" name="authenticity_token" value=#{form_authenticity_token}>'
    text.html_safe
  end
end

Reddit/app/helpers/posts_helper.rb
module PostsHelper
end

Reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit/app/helpers/users_helper.rb
module UsersHelper
end

Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %>
    <% end %>
    <% end %>
<%= yield %>

</body>
</html>

Reddit/app/views/posts/_form.html.erb
<% action_url = @post.id.nil? ? sub_posts_url(sub_id: params[:sub_id]) : sub_post_url(@post.sub_id, @post.id) %>
<% method_1 = @post.id.nil? ? "post" : "put" %>

<form  action = "<%= action_url %>"  method= "post" >
  <% unless @post.id.nil? %>
  <%= "<input type=\"hidden\" name=\"_method\" value=\"put\">".html_safe %>
  <% end %>
  <%= auth_token %>
  <label>Title</label>
  <input type="text" name="post[title]" value= "<%= @post.id.nil? ? "" : @post.title%>"><br>
  <label>Url</label>
  <input type="text" name="post[url]" value= "<%= @post.id.nil? ? "" : @post.url %>"><br>
  <label>Content</label>
  <input type="text" name="post[content]" value= "<%= @post.id.nil? ? "" : @post.content %>"><br>
  <% Sub.all.each do |sub| %>
    <input type="checkbox" name="post[sub_id][]" value="<%= sub.id %>"
    <%= "checked" unless @post.id.nil? %> ><%= sub.title %><br>
  <% end %>
  <input type="submit"  value=" <%= @post.id.nil? ? "Create post" : "Edit post" %>">
</form>

Reddit/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_url(id: params[:sub_id]) %>

Reddit/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_url(id: params[:sub_id]) %>

Reddit/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @post.title %> by <%= @post.author.username %></h1>

<div class="small-border"
    <b>Content:</b>

    <pre><%= @post.content %></pre>
    <br><br>
  </div>

<% if current_user.id == @post.author.id %>
  <%= link_to 'Edit', edit_sub_post_url(@post.sub_id, @post.id) %>
<% end %>
<%= link_to 'Back', sub_url(id: params[:sub_id]) %>

Reddit/app/views/subs/_form2.html.erb
<% action_url = @sub.id.nil? ? user_subs_url : user_sub_url(@sub.id) %>
<% method_1 = @sub.id.nil? ? "post" : "put" %>

<form  action = "<%= action_url %>"  method= "<%= method_1 %>" >
  <%= auth_token %>
  <label>Title</label>
  <input type="text" name="sub[title]" value= "<%= @sub.id.nil? ? "" : @sub.title%>"><br>
  <label>Description</label>
  <input type="text" name="sub[description]" value= "<%= @sub.id.nil? ? "" : @sub.description %>"><br>
  <input type="submit"  value=" <%= @sub.id.nil? ? "Create Sub" : "Edit sub" %>">
</form>

Reddit/app/views/subs/edit.html.erb
<h1>Editing Sub</h1>

<%= render 'form2' %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

Reddit/app/views/subs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Moderator</th>
      <th colspan="40"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= link_to  sub.title, sub_url(sub.id) %></td>
        <td><%= sub.description %></td>
        <td><%= sub.moderator.username %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_user_sub_url(current_user.id) %>

Reddit/app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render 'form2' %>

<%= link_to 'Back', subs_path %>

Reddit/app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sub.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sub.description %>
</p>

<p>
  <strong>Moderator:</strong>
  <%= @sub.moderator_id %>
</p>

<ul>
<% @sub.posts.each do |post| %>
  <li> <%= link_to post.title, sub_post_url(post.sub_id, post.id) %></li>
<% end %>
</ul>
<%= link_to 'Create post', new_sub_post_url(@sub.id) %><br><br>
<%= link_to 'Edit', edit_user_sub_url(@sub.moderator_id, @sub.id) %> |
<%= link_to 'Back', subs_path %>
<td><%= link_to 'Destroy', user_sub_url(@sub.moderator_id, @sub.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>

Reddit/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Reddit/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Reddit/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Reddit/app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%=users_url%>" method="post">
  <%= auth_token %>
  <label>Username</label>
  <input type="text" name="user[username]"><br>
  <label>Passsword</label>
  <input type="password" name="user[password]">
  <input type="submit" value"Create User">
</form>

<%= link_to 'Back', users_path %>

Reddit/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<%= button_to 'LogOut', session_url, method: "delete" %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>